sls:
  url: ${SLS_HOST_URL}

hapi-fhir:
  url: ${HAPI_FHIR_URL}

spring:
  datasource:
    url: jdbc:google:mysql://${CLOUD_SQL_CONNECTION_NAME}/${DB_NAME}?cloudSqlInstance=&socketFactory=com.google.cloud.sql.mysql.SocketFactory&autoReconnect=true&useSSL=false
